name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
  
    - name: Install uv
      run: python -m pip install uv
  
    - name: Generate requirements.txt from pyproject.toml
      run: uv pip compile pyproject.toml > requirements.txt

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest
