name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      VIRUS_TOTAL_API_KEY: ${{ secrets.VIRUS_TOTAL_API_KEY }}
      SAFE_BROWSING_API_KEY: ${{ secrets.SAFE_BROWSING_API_KEY }}
      MONGO_DB_CONNECTION_STRING: ${{ secrets.MONGO_DB_CONNECTION_STRING }}
      BETTER_STACK_SOURCE_TOKEN: ${{ secrets.BETTER_STACK_SOURCE_TOKEN }}
      BETTER_STACK_INGESTING_HOST: ${{ secrets.BETTER_STACK_INGESTING_HOST }}


    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.5"
    
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
  
    - name: Install uv
      run: python -m pip install uv
  
    - name: Generate requirements.txt from pyproject.toml
      run: uv pip compile pyproject.toml > requirements.txt

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt
    
    - name: Install pytest-asyncio
      run: pip install pytest-asyncio

    - name: Run tests
      run: PYTHONPATH=$(pwd) pytest
